### PR TITLE
OMAYGOTTT AMBATABUSS AMBATABUSSS OMAYLUWDDDDD FUCkkk....

### PR DESCRIPTION
**Pull request by jah255**
auagh shit am batta buss ambatabuss a load fuacck,....

### CODE REVIEW

**Comment by jah255** [comment]
NIGGER

**Comment by jah255** [comment]
@everyone nigga

**Comment by jah255** [comment]
kill all nigga bal

**Comment by jah255** [comment]
:fr_emoji:

**Comment by BigBoiMan123** [comment]
why

**Comment by guacaplushy** [comment]
skull

**Pull request closed without merging**
