### PR TITLE
Fixed grammar

### PR DESCRIPTION
**Pull request by jah255**
Made the grammar more clear and more understandable.

### CODE REVIEW

**Comment by mineek** [comment]
whar

**Comment by jah255** [comment]
:insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji::insert_fr_emoji:

**Comment by jah255** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by jah255** [comment]
e2bc1913-7422-4d8f-86fd-addeecefb194

**Comment by jah255** [comment]
please merge this i fixed the grammar in readme

**Comment by mineek** [comment]
how about no

**Comment by jah255** [comment]
fr emoji

**Comment by jah255** [comment]
fr emoji

**Comment by jah255** [comment]
fr emoji coal

**Comment by Beast9265** [comment]
someone ban them from the github

**Pull request closed without merging**
