### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vadim-a-yegorov**
Added https://t.me/palera1nchat

### CODE REVIEW

**Comment by lawyoum** [comment]
👍🏻

**Comment by vadim-a-yegorov** [comment]
@itsnebulalol

**Review by lawyoum — APPROVED** [review]

**Comment by flowerible** [comment]
why a non-official telegram

**Comment by TheMasterOfMike** [comment]
Telegram is kinda shit.

An unofficial telegram is even worse (and bound to just become a piracy/iCloud Bypass haven like 90% of jailbreaking telegrams are)

**Comment by itsnebulalol** [comment]
I'm admin in it but I don't really like telegram anyway. Random people have custom roles which means they have some sort of mod perm. I might end up making an official one but idk

**Comment by flowerible** [comment]
If you're not gonna be active then no point tbh, also have you ever seen the jb_ telegram holy it's so bad (in terms of UX and multiple channels)

**Comment by flowerible** [comment]
it's so awful to use

**Comment by itsnebulalol** [comment]
Telegram spaces kind of improved it but its really bad to moderate

**Pull request closed without merging**
